name: "slack-deploy-notify"

description: "slack deploy notifying"

inputs:
  title:
    description: "title for deployed service"
    required: true
  url:
    description: "site url for deployed service"
    required: true
  slack_webhook_url:
    description: "slack webhook url"
    required: true

runs:
  using: "composite"
  steps:
    - name: notify
      uses: 8398a7/action-slack@v3.13.2
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.slack_webhook_url }}
        STEP_TITLE: ${{ inputs.title }}
        SITE_URL: "<${{ inputs.url }}|${{ inputs.url }}>"
      with:
        status: custom
        fields: commit,repo,ref,author,took
        custom_payload: |
          {
            attachments: [{
              color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
              text: `${'${{ job.status }}' === 'success' ? '✅' : '${{ job.status }}' === 'failure' ? '⛔' : '⚠'} ${process.env.STEP_TITLE}\nSITE_URL: ${process.env.SITE_URL}\n${process.env.AS_COMMIT} of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} ${{ job.status }} in ${process.env.AS_TOOK}`,
            }]
          }
