name: "Test"

on: push

jobs:
  test-job:
    name: test test

    runs-on: ["self-hosted", "Linux", "X64"]

    steps:
      - name: chekcout
        uses: actions/checkout@v3

      - name: say hello
        run: echo "제톰이짱"

      - name: Notify Slack
        if: always()
        uses: ./.github/actions/slack-deploy-notify
        with:
          title: "testsetste"
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
